spring:
  application:
    name: service
  jackson:
    deserialization:
      accept-float-as-int: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          client-id: 208958545173-sl0jq18aaa9o4mm56hvp786k3d00fbg6.apps.googleusercontent.com


server:
  port: 8081
  servlet:
    context-path: /codebreaker-community
  error:
    include-message: always
  forward-headers-strategy: native


